### ISSUE TITLE
Building docker fails

### ISSUE THREAD

**Issue by nomelif** [theNewFlesh/docker_pyopenvdb#1]
Hi.

I am trying to build the docker image as per instructions. I am on linux x64. Docker-compose dies in the middle of apt update (repositories not having release files).

This does not happen if I edit the docker-compose.yaml to point to the prod docker file. An oversight?

**Comment by theNewFlesh** [comment]
pyopenvdb.dockerfile is the dockerfile used for developing and publishing the pyopenvdb package
pyopenvdb_prod.dockerfile is just a dockerfile that installs pyopenvdb via pip

The point of this repo is to pip package pyopenvdb so that you can install it with pip, not to give you some fancy docker container for using openvdb, that's just a bonus. If you want a container to use pyopenvdb with then go with pyopenvdb_prod.dockerfile or copy the contents therein.

I probably need to update pyopenvdb.dockerfile to use ubuntu 20.04, I imagine I didn't;t before because of c library dependency hell. Try changing FROM ubuntu:19.04 in the that file to ubuntu:20.04

20.04 is a LTS version of ubuntu, so it probably breaks less.

**Comment by nomelif** [comment]
Ah, thank you for the clarification. Would it be possible to have a version for Python 3.8 too on PyPi then?

**Comment by theNewFlesh** [comment]
Try pip installing it with python3.8, it may already work

**Comment by theNewFlesh** [comment]
Nevermind it doesn't.

**Comment by theNewFlesh** [comment]
Python3.8 now supported. Pip install pyopenvdb-3.8, make sure its version 0.1.5 or greater.
Tested on fresh ubuntu 20.04 container and it works. Also checkout the python3.8 branch if you want to review the changes.
