### ISSUE TITLE
libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by FryeKai** [theNewFlesh/docker_pyopenvdb#4]
>> import pyopenvdb
gives this error:
>>ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

I think I have a working environment for python 3.7, but I cannot seem to make it work.

However, I would appreciate support for python 3.8 or higher.

**Comment by theNewFlesh** [comment]
I already have a [branch](https://github.com/theNewFlesh/docker_pyopenvdb/tree/python3.8) and a published [package](https://pypi.org/project/pyopenvdb-3.8/) for python3.8.

The pyopenvdb packages (3.7 and 3.8) are not intended to work in general environments. Rather they have only been confirmed to work on Linux x86 systems. More specifically, they are designed to work within the docker containers already provided by this project. Those containers contain the correct python, C and C++ dependencies.

I suggest you clone the repo under the python3.8 branch and boot up the container therein, via `bin/pyopenvdb start`. Be sure to folow the dev installation instructions. Or build your own ubuntu 20.04 image and copy and paste the dependencies found in pyopenvdb.dockerfile. Installing a native linux system is a more dicey prospect (kinda the reason docker exists in the first place), but go ahead if you want.

**Comment by FryeKai** [comment]
Hi
turns out, I am really stupid on this one, because I can not make it work.

* I have installed pyopenvdb using  _pip install pyopenvdb-3.8_  ...But I still get the error above.
* I am working on ubuntu 20.04
* I have no idea about docker and I try to avoid it. 
* I followed the installation guide from this thread: https://github.com/AcademySoftwareFoundation/openvdb/discussions/1149

Any chance to make it work without docker?

Cheers,
Kai

**Comment by theNewFlesh** [comment]
I ran:
```
docker --rm -it ubuntu:20.04
apt update
apt install -y \
    python3-dev \
    curl
curl https://bootstrap.pypa.io/get-pip.py -O get-pip.py
python3.8 get-pip.py
pip3.8 install pyopenvdb-3.8
find / | grep pyopenvdb.so   # to find the parent folder of this file
export LD_LIBRARY_PATH=/usr/local/lib/python3.8/dist-packages

python3.8
import openvdb
```
and it worked just fine.

This means that a vanilla install of ubuntu 20.04 plus these apt packages will run it correctly.

> I have no idea about docker and I try to avoid it.

Docker is a container technology that runs an entire linux OS, without hardware virtualization, as a process on your computer (a cGroup). This enables you to have complete control over the software and dependencies inside said environment.

Package installation and management for C and C++ is miserable, no tools as easy as pip or node exist to solve this problem. Unfortunately, a huge amount of software is written in these two languages, including python and many libraries it depends on, such as OpenVDB. Rather than trying to solve the problem of installing C and C++ libraries on an existing system with its own complications, Docker is used to wipe the slate clean, and let you install things in a known environment. What's even better is that, other people can do that for you, save that environment as a docker image and publish it to the web for you to download (`docker pull`).

For example:
```
▶ docker pull thenewflesh/pyopenvdb
latest: Pulling from thenewflesh/pyopenvdb
da7391352a9b: Pull complete 
14428a6d4bcd: Pull complete 
2c2d948710f2: Pull complete 
Status: Downloaded newer image for thenewflesh/pyopenvdb:latest
▶ docker run --rm -it thenewflesh/pyopenvdb
root@bb2e8e49e0cd:~# python3.7
>>> import openvdb
```

I can publish a python3.8 version of pyopenvdb to dockerhub. But if you wish to install pyopenvdb in your host OS rather than inside docker, that's up to you.
